enhancedfields_image_upload_temp:
  path: /enhancedfields/image/upload-temp
  methods: [ POST ]
  defaults:
    _controller: PrestaShop\Module\EnhancedFields\Controller\ImageController::uploadTempAction

enhancedfields_image_fetch:
  path: /enhancedfields/image/fetch/{location}/{filename}
  methods: [ GET ]
  defaults:
    _controller: PrestaShop\Module\EnhancedFields\Controller\ImageController::fetchAction
  requirements:
    filename: .+
